#!/bin/sh
# Script to automatically restart a program
# Usage: keepalive 

WORKING_DIR=`pwd`

if [ $# -lt 1 ]; then
        echo "Usage: $0 "
        exit
fi

while true
do
        cd $WORKING_DIR
        #launch the process
        $@
        sleep 1
        echo "Restarting."
done